### ISSUE TITLE
Codigo

### ISSUE THREAD

**Issue by DamRCorba** [Nico2703/TP-MaquinaDeEstados-PesadorDeCarga#2]
Hola nicolas, en lineas generales esta bien. Solo que abusaste de la separacion de archivos. Por lo general es buena practica la separacion pero no el abuso. En tu caso hiciste un archivo por funcion, lo logico es agrupar a las funciones de un mismo fin en un solo archivo. En el caso de tu programa deberias tener un archivo main solo con el main y un archivo de estados con todas las funcioens de tus estados.

**Comment by Nico2703** [comment]
Entendido Damián.
Corrijo entonces. Entendí mal ese ítem.
Gracias!!
Saludos!

**Comment by DamRCorba** [comment]
Tp Aprobado

**Comment by Nico2703** [comment]
Recibido Damián.
Muchas gracias.
Saludos!
