### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by Nico2703** [Nico2703/TP-MaquinaDeEstados-PesadorDeCarga#3]
Que tal Damián??
Tengo una duda acerca de la agrupación de las funciones.

Por lo que entiendo, me quedaría por un lado un archivo "main".
Otro archivo, digamos, "estados", el cual tendría dentro a las funciones de espera, carga máxima y sobrecarga.
Y otro archivo, digamos "ajuste", el cual tendría a las funciones de carga inicial, y de simulación del sensor.
Esta división sería correcta??

Si es así, como debería hacer las llamadas a las funciones ??
Entiendo que en el "main" debería llamar a las funciones de "estados" y "ajuste". 
Y luego, dentro de "estados" o "ajuste" llamar a cada función particular.
Cúal sería la mejor manera de hacer esto?
Debería generar una variable para que solo entre una vez a la función de inicio?
Por lo que estuve probando, esto traerá conflictos entre variables, y el puntero "*fsm" ya no debería estar definido en el "main".

El programa lo inicié en un unico "main" y luego lo subdividí en funciones individuales.
No logro darme cuenta como debo reorganizar todos los datos.

Gracias por tu tiempo!
Saludos.

**Comment by DamRCorba** [comment]
Justamente para esas cosas es el tp. La division de archivos es correcta. Vas a tener un archivo .h que contenga todos los prototipos de todas las funciones que estaras desarrollando en cada archivo, ese archivo sera el nexo entrelos .c
En cuanto al puntero, si lo abris en el main y lo tenes que usar en las demas funciones deberias hacer que llegue a ellas. Tenes varias opciones, una es como variable global, lo cual es mala práctica, y no deberias usarlo. Y las otras es usando los parametros de las funciones, ya sea con pasaje por valor o referencia

Enviado desde Yahoo Mail con Android 
 
  El mar., sept. 15, 2020 a 18:56, NicoFerra<notifications@github.com> escribió:   


Que tal Damián??
Tengo una duda acerca de la agrupación de las funciones.

Por lo que entiendo, me quedaría por un lado un archivo "main".
Otro archivo, digamos, "estados", el cual tendría dentro a las funciones de espera, carga máxima y sobrecarga.
Y otro archivo, digamos "ajuste", el cual tendría a las funciones de carga inicial, y de simulación del sensor.
Esta división sería correcta??

Si es así, como debería hacer las llamadas a las funciones ??
Entiendo que en el "main" debería llamar a las funciones de "estados" y "ajuste".
Y luego, dentro de "estados" o "ajuste" llamar a cada función particular.
Cúal sería la mejor manera de hacer esto?
Debería generar una variable para que solo entre una vez a la función de inicio?
Por lo que estuve probando, esto traerá conflictos entre variables, y el puntero "*fsm" ya no debería estar definido en el "main".

El programa lo inicié en un unico "main" y luego lo subdividí en funciones individuales.
No logro darme cuenta como debo reorganizar todos los datos.

Gracias por tu tiempo!
Saludos.

**Comment by Nico2703** [comment]
Gracias por la pronta respuesta Damián!
Sigo trabajando al respecto.
Te contacto cualquier otra duda.
